Traceback (most recent call last):
  File "/home/carlotta.giacchetta/AlphatensorFinal/parallel_main.py", line 61, in <module>
    run(test=args.test)
  File "/home/carlotta.giacchetta/AlphatensorFinal/parallel_main.py", line 37, in run
    model = TensorModel(dim_3d=4, dim_t=8, dim_s=1, dim_c=16, n_steps=12, n_logits=3, n_samples=4, device=args["device"]).to(args["device"])
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/carlotta.giacchetta/AlphatensorFinal/model.py", line 732, in __init__
    self.torso = TorsoGCNv2(S=4, hidden_dim=128, dim_c=dim_c)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: TorsoGCNv2.__init__() got an unexpected keyword argument 'dim_c'
